services:
  beautyscheduler.api:
    image: ${DOCKER_REGISTRY-}beautyschedulerapi
    build:
      context: .
      dockerfile: src/BeautyScheduler.Api/Dockerfile
    depends_on:
      - postgres
    networks:
      - app_network
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: BeautySchedulerDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network  
volumes:
  postgres_data:

networks:
  app_network: 
